"""first migration of gosh so many tries

Revision ID: a3155895b0c7
Revises: 
Create Date: 2024-01-04 17:13:00.258829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3155895b0c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('munchkins',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('munchkin', sa.String(length=80), nullable=False),
    sa.Column('parent', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('munchkin', sa.String(length=80), nullable=False),
    sa.Column('parent', sa.String(length=80), nullable=False),
    sa.Column('sleeptime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep_times')
    op.drop_table('parents')
    op.drop_table('munchkins')
    # ### end Alembic commands ###
